repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--rcfile=.pylintrc, "--msg-template=\"{path}({line}): [{obj}] {msg} ({symbol})\""]
      - id: markdownlint
        name: markdownlint
        entry: markdownlint
        language: system
        types: [markdown]
        args: [--config=.markdownlint.json]